.PHONY: clean All

All:
	@echo "----------Building project:[ Zadanie45 - Debug ]----------"
	@cd "Zadsnie4" && "$(MAKE)" -f  "Zadanie45.mk"
clean:
	@echo "----------Cleaning project:[ Zadanie45 - Debug ]----------"
	@cd "Zadsnie4" && "$(MAKE)" -f  "Zadanie45.mk" clean
