.PHONY: clean All

All:
	@echo "----------Building project:[ Zadanie1 - Debug ]----------"
	@cd "Zadanie1" && "$(MAKE)" -f  "Zadanie1.mk"
clean:
	@echo "----------Cleaning project:[ Zadanie1 - Debug ]----------"
	@cd "Zadanie1" && "$(MAKE)" -f  "Zadanie1.mk" clean
