.PHONY: clean All

All:
	@echo "----------Building project:[ Zadanie6 - Debug ]----------"
	@cd "Zadanie6" && "$(MAKE)" -f  "Zadanie6.mk"
clean:
	@echo "----------Cleaning project:[ Zadanie6 - Debug ]----------"
	@cd "Zadanie6" && "$(MAKE)" -f  "Zadanie6.mk" clean
