.PHONY: clean All

All:
	@echo "----------Building project:[ Zadanie2 - Debug ]----------"
	@cd "Zadanie2" && "$(MAKE)" -f  "Zadanie2.mk"
clean:
	@echo "----------Cleaning project:[ Zadanie2 - Debug ]----------"
	@cd "Zadanie2" && "$(MAKE)" -f  "Zadanie2.mk" clean
