.PHONY: clean All

All:
	@echo "----------Building project:[ Zadanie4 - Debug ]----------"
	@cd "Zadanie4" && "$(MAKE)" -f  "Zadanie4.mk"
clean:
	@echo "----------Cleaning project:[ Zadanie4 - Debug ]----------"
	@cd "Zadanie4" && "$(MAKE)" -f  "Zadanie4.mk" clean
