.PHONY: clean All

All:
	@echo "----------Building project:[ Zadanie5 - Debug ]----------"
	@cd "Zadanie5" && "$(MAKE)" -f  "Zadanie5.mk"
clean:
	@echo "----------Cleaning project:[ Zadanie5 - Debug ]----------"
	@cd "Zadanie5" && "$(MAKE)" -f  "Zadanie5.mk" clean
