.PHONY: clean All

All:
	@echo "----------Building project:[ Zadanie567 - Debug ]----------"
	@cd "Zadanie567" && "$(MAKE)" -f  "Zadanie567.mk"
clean:
	@echo "----------Cleaning project:[ Zadanie567 - Debug ]----------"
	@cd "Zadanie567" && "$(MAKE)" -f  "Zadanie567.mk" clean
